import { CategoryInfo, Template } from "@/types/template";
import { SurpriseExperience } from "@/types/experience";

export const BRAND_NAME = "Partner in Crime";
export const BRAND_HEADLINE = "DON’T JUST SEND A WISH. SEND A SURPRISE.";
export const BRAND_SUBTITLE = "Create a tiny interactive experience for someone’s special day.";
export const BRAND_SUPPORTING_LINE = "A message takes seconds to read. A surprise becomes a memory.";

export const NAV_LINKS = [
  { label: "Birthday", href: "/birthday" },
  { label: "Explore", href: "/templates" },
  { label: "How It Works", href: "/#how-it-works" },
] as const;

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "birthday",
    name: "Birthday & Celebrations",
    description: "Cakes, candles to blow out, confetti pop, and emotional polaroids.",
    iconName: "Cake",
    badgeColor: "bg-pink-500/10 text-pink-600 border-pink-200 dark:border-pink-800 dark:text-pink-300",
    accentColor: "from-pink-500 to-rose-500",
    isPopular: true,
  },
  {
    id: "anniversary",
    name: "Anniversary",
    description: "Timeline of our memories, glowing lanterns, and heartfelt letters.",
    iconName: "HeartHandshake",
    badgeColor: "bg-purple-500/10 text-purple-600 border-purple-200 dark:border-purple-800 dark:text-purple-300",
    accentColor: "from-purple-500 to-indigo-500",
    isPopular: true,
  },
  {
    id: "love",
    name: "Love & Romance",
    description: "Romantic starfield, floating origami hearts, and love notes.",
    iconName: "Heart",
    badgeColor: "bg-rose-500/10 text-rose-600 border-rose-200 dark:border-rose-800 dark:text-rose-300",
    accentColor: "from-rose-500 to-red-500",
    isPopular: true,
  },
  {
    id: "friendship",
    name: "Best Friend",
    description: "Inside jokes, memorable roast cards, and quirky celebration themes.",
    iconName: "Smile",
    badgeColor: "bg-amber-500/10 text-amber-600 border-amber-200 dark:border-amber-800 dark:text-amber-300",
    accentColor: "from-amber-500 to-orange-500",
    isPopular: true,
  },
  {
    id: "proposal",
    name: "Proposal & Rings",
    description: "Immersive ring box opening with soft cinematic orchestral music.",
    iconName: "Gem",
    badgeColor: "bg-cyan-500/10 text-cyan-600 border-cyan-200 dark:border-cyan-800 dark:text-cyan-300",
    accentColor: "from-cyan-500 to-blue-500",
  },
  {
    id: "wedding",
    name: "Wedding Wishes",
    description: "Floral archways, golden confetti, and congratulations guestbook.",
    iconName: "Sparkles",
    badgeColor: "bg-emerald-500/10 text-emerald-600 border-emerald-200 dark:border-emerald-800 dark:text-emerald-300",
    accentColor: "from-emerald-500 to-teal-500",
  },
  {
    id: "congratulations",
    name: "Congratulations",
    description: "Fireworks celebration, trophy reveal, and achievement highlights.",
    iconName: "Trophy",
    badgeColor: "bg-yellow-500/10 text-yellow-600 border-yellow-200 dark:border-yellow-800 dark:text-yellow-300",
    accentColor: "from-yellow-500 to-amber-500",
  },
  {
    id: "festivals",
    name: "Festivals & Holidays",
    description: "Diwali diyas, Christmas snowfall, Durga Puja dhak, and New Year countdown.",
    iconName: "Flame",
    badgeColor: "bg-violet-500/10 text-violet-600 border-violet-200 dark:border-violet-800 dark:text-violet-300",
    accentColor: "from-violet-500 to-fuchsia-500",
  },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "tpl-magic-gift",
    slug: "magic-gift",
    name: "Magic Gift 🎁",
    category: "birthday",
    description: "The signature 3D unboxing experience. Features cinematic camera sweeps, rewarding tap sequence, blowable cake, and personal note.",
    tagline: "Unwrap the magic of a real celebration.",
    tags: ["Signature", "3D Gift", "Unboxing", "Cinematic", "Letter", "Balloons"],
    thumbnailUrl: "/thumbnails/magic-gift.jpg",
    coverGradient: "from-pink-500 via-rose-500 to-amber-400",
    sceneCount: 7,
    estimatedDuration: "2-3 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-birthday-cake",
    slug: "birthday-cake-reveal",
    name: "Birthday Cake Reveal 🎂",
    category: "birthday",
    description: "An enchanting sweet celebration featuring a multi-tiered cake, candle lighting, tap-to-blow wish, and grand confetti finale.",
    tagline: "Make a wish and watch the magic unfold.",
    tags: ["3D Cake", "Candle Wish", "Sweet", "Confetti", "Letter"],
    thumbnailUrl: "/thumbnails/birthday-cake.jpg",
    coverGradient: "from-amber-400 via-pink-500 to-purple-600",
    sceneCount: 9,
    estimatedDuration: "2 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-balloon-room",
    slug: "balloon-room",
    name: "Balloon Room 🎈",
    category: "birthday",
    description: "Open the birthday room door into an immersive balloon cloud that dynamically spells out the recipient's name in mid-air.",
    tagline: "Step inside a room overflowing with joy.",
    tags: ["Balloons", "Immersive Room", "Name Formation", "Joyful"],
    thumbnailUrl: "/thumbnails/balloon-room.jpg",
    coverGradient: "from-sky-400 via-blue-500 to-indigo-600",
    sceneCount: 9,
    estimatedDuration: "2-3 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-mystery-door",
    slug: "mystery-door",
    name: "Mystery Door 🚪",
    category: "birthday",
    description: "A mysterious glowing door appears in a magical hallway. Unlock it to enter an enchanting celebration room with character gift delivery.",
    tagline: "Turn the handle to unlock what is waiting.",
    tags: ["3D Door", "Secret Room", "Character Delivery", "Adventure"],
    thumbnailUrl: "/thumbnails/mystery-door.jpg",
    coverGradient: "from-indigo-600 via-purple-600 to-pink-500",
    sceneCount: 10,
    estimatedDuration: "3 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-memory-journey",
    slug: "memory-journey",
    name: "Memory Journey 📸",
    category: "birthday",
    description: "A nostalgic photographic voyage. Floating polaroids of cherished memories assemble into a glowing heart constellation.",
    tagline: "Walk down memory lane together.",
    tags: ["Photos", "Polaroids", "Nostalgic", "Heart Constellation", "Emotional"],
    thumbnailUrl: "/thumbnails/memory-journey.jpg",
    coverGradient: "from-amber-500 via-orange-400 to-rose-400",
    sceneCount: 10,
    estimatedDuration: "3 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-confetti-blast",
    slug: "confetti-blast",
    name: "Confetti Blast 🎉",
    category: "birthday",
    description: "A fast-loading, lightning-paced birthday countdown experience featuring dramatic 3-2-1 suspense and a massive confetti explosion.",
    tagline: "Countdown to the loudest birthday cheer.",
    tags: ["Fast Loading", "Countdown", "Huge Confetti", "High Energy", "Party"],
    thumbnailUrl: "/thumbnails/confetti-blast.jpg",
    coverGradient: "from-yellow-400 via-pink-500 to-red-500",
    sceneCount: 9,
    estimatedDuration: "1-2 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-rainbow-surprise",
    slug: "rainbow-surprise",
    name: "Rainbow Surprise 🌈",
    category: "birthday",
    description: "A magical storybook landscape where a playful companion chases a glowing rainbow into a vibrant birthday wonderland.",
    tagline: "Follow the vibrant rainbow to a secret birthday world.",
    tags: ["Magical", "Rainbow", "Character", "Storybook", "Joyful"],
    thumbnailUrl: "/thumbnails/rainbow-surprise.jpg",
    coverGradient: "from-emerald-400 via-teal-500 to-fuchsia-500",
    sceneCount: 8,
    estimatedDuration: "2 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-cute-character",
    slug: "cute-character",
    name: "Cute Character 🧸",
    category: "birthday",
    description: "An endearing animated 3D companion carries, delivers, and opens a personalized gift box filled with joy.",
    tagline: "A cuddly messenger delivering your love.",
    tags: ["Character", "Cute", "Mascot", "Interactive", "Heartwarming"],
    thumbnailUrl: "/thumbnails/cute-character.jpg",
    coverGradient: "from-amber-400 via-orange-500 to-rose-500",
    sceneCount: 11,
    estimatedDuration: "3 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-sweet-celebration",
    slug: "sweet-celebration",
    name: "Sweet Celebration 💌",
    category: "birthday",
    description: "A heartwarming pastel birthday celebration with bouncing party flags, polaroid frame, animated balloons, typewriter letterbox, and real-time heart cursor trail.",
    tagline: "A heartwarming celebration with an interactive letterbox.",
    tags: ["Interactive Letter", "Pastel", "Typewriter", "Photo Polaroid", "Sweet", "Heart Cursor"],
    thumbnailUrl: "/templates/sweet-celebration/thumbnail.jpg",
    coverGradient: "from-pink-400 via-rose-400 to-amber-300",
    sceneCount: 3,
    estimatedDuration: "2 mins",
    isFeatured: true,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-love-01",
    slug: "origami-hearts-sanctuary",
    name: "Floating Origami Sanctuary",
    category: "love",
    description: "Delicate paper cranes and glowing heart origami floating over serene reflection waters.",
    tagline: "Every fold holds a reason I cherish you.",
    tags: ["Romantic", "Origami", "Orchestral", "Gentle"],
    thumbnailUrl: "/thumbnails/origami.jpg",
    coverGradient: "from-rose-500 via-red-400 to-purple-600",
    sceneCount: 3,
    estimatedDuration: "2 mins",
    isFeatured: false,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-anniv-01",
    slug: "golden-milestone-journey",
    name: "Golden Milestone Lanterns",
    category: "anniversary",
    description: "Release illuminated sky lanterns into twilight clouds marking each year you've celebrated together.",
    tagline: "To all our yesterdays and every tomorrow.",
    tags: ["Lanterns", "Twilight", "Milestones", "Golden"],
    thumbnailUrl: "/thumbnails/lanterns.jpg",
    coverGradient: "from-violet-600 via-purple-500 to-amber-400",
    sceneCount: 4,
    estimatedDuration: "3 mins",
    isFeatured: false,
    isNew: false,
    isPremium: false,
    defaultScenes: [],
  },
  {
    id: "tpl-friend-01",
    slug: "roast-and-toast-squad",
    name: "The Ultimate Roast & Toast",
    category: "friendship",
    description: "Hilarious interactive scratch-cards, funny inside jokes, and a joyful trophy reveal at the end.",
    tagline: "Because normal birthday cards are too boring for best friends.",
    tags: ["Funny", "Interactive Cards", "Trophy", "Party"],
    thumbnailUrl: "/thumbnails/roast.jpg",
    coverGradient: "from-yellow-400 via-amber-500 to-red-500",
    sceneCount: 3,
    estimatedDuration: "2 mins",
    isFeatured: false,
    isNew: true,
    isPremium: false,
    defaultScenes: [],
  },
];

export const SAMPLE_SURPRISE: SurpriseExperience = {
  id: "exp-sample-001",
  publicId: "sample-birthday-123",
  userId: "user-demo-1",
  title: "Maya's 25th Magical Birthday",
  category: "birthday",
  templateId: "tpl-bday-01",
  recipient: {
    name: "Maya",
    relationship: "Best Friend",
    birthDate: "2026-09-14",
  },
  sender: {
    name: "Alex",
    relationship: "Best Friend",
  },
  scenes: [
    {
      id: "sc-1",
      sceneType: "intro-gift-box",
      order: 1,
      title: "Tap To Unwrap Your Surprise",
      subtitle: "Made with love, just for Maya",
      customText: "You thought I'd just send a boring text? Think again!",
    },
    {
      id: "sc-2",
      sceneType: "cake-candles",
      order: 2,
      title: "Make Your 25th Wish!",
      subtitle: "Tap the candles to blow them out",
      customText: "May this year bring you all the joy, success, and laughter in the universe!",
    },
  ],
  photos: [
    {
      id: "p1",
      url: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop",
      caption: "That spontaneous road trip adventure!",
    },
    {
      id: "p2",
      url: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600&auto=format&fit=crop",
      caption: "Always finding reasons to laugh together.",
    },
  ],
  customMessage: "Happy Birthday Maya! You are one of the brightest lights in my life. Thank you for always being there through thick and thin. Here is to another year of big adventures!",
  status: "published",
  viewCount: 14,
  createdAt: "2026-09-12T10:00:00Z",
  updatedAt: "2026-09-12T10:30:00Z",
};
